<?php
return array(
    "fallback" => null,
    "formatter" => "basic",
    "messages" => [
    
        "FILTER_RULE_FAILURE_IS_ALNUM" => "Bitte nur alphanumerische Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_ALNUM" => "Bitte nicht nur alphanumerische Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_ALNUM" => "Bitte frei lassen oder nur alphanumerische Zeichen verwenden.",
        "FILTER_RULE_FAILURE_FIX_ALNUM" => "Umwandlung in nur alphanumerische Zeichen nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_ALNUM" => "Umwandlung in leeren Wert oder nur alphanumerische Zeichen nicht möglich.",

        "FILTER_RULE_FAILURE_IS_ALPHA" => "Bitte nur Buchstaben verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_ALPHA" => "Bitte nicht nur Buchstaben verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_ALPHA" => "Bitte frei lassen oder nur Buchstaben verwenden.",
        "FILTER_RULE_FAILURE_FIX_ALPHA" => "Umwandlung zu nur Buchstaben nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_ALPHA" => "Umwandlung in leeren Wert oder nur Buchstaben nicht möglich.",

        "FILTER_RULE_FAILURE_IS_ANY" => "Dieses Feld hat keine der Sub-Regel bestanden.",
        "FILTER_RULE_FAILURE_IS_NOT_ANY" => "Dieses Feld hätte keine der Sub-Regel bestehen sollen.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_ANY" => "Bitte frei lassen oder so verändern, dass die Sub-Regeln bestanden werden.",
        "FILTER_RULE_FAILURE_FIX_ANY" => "Umwandlung dieses Feldes nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_ANY" => "Umwandlung dieses Feldes nicht möglich.",

        "FILTER_RULE_FAILURE_IS_BETWEEN" => "Bitte einen Wert zwischen {min} und {max} eingeben.",
        "FILTER_RULE_FAILURE_IS_NOT_BETWEEN" => "Bitte einen Wert eingeben, der nicht zwischen {min} und {max} liegt.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_BETWEEN" => "Bitte frei lassen oder einen Wert zwischen {min} und {max} eingeben.",
        "FILTER_RULE_FAILURE_FIX_BETWEEN" => "Umwandlung zu einem Wert zwischen {min} und {max} nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_BETWEEN" => "Umwandlung in einen leeren Wert oder einem Wert zwischen {min} und {max} nicht möglich.",

        "FILTER_RULE_FAILURE_IS_BLANK" => "Bitte dieses Feld leer lassen.",
        "FILTER_RULE_FAILURE_IS_NOT_BLANK" => "Bitte dieses Feld nicht leer lassen.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_BLANK" => "Bitte dieses Feld leer lassen.",
        "FILTER_RULE_FAILURE_FIX_BLANK" => "Umwandlung zu leerem Wert nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_BLANK" => "Umwandlung zu leerem Wert nicht möglich.",

        "FILTER_RULE_FAILURE_IS_BOOL" => "Bitte einen booleschen Wert (true/false) verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_BOOL" => "Bitte keinen booleschen Wert (true/false) verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_BOOL" => "Bitte frei lassen oder einen booleschen Wert (true/false) verwenden.",
        "FILTER_RULE_FAILURE_FIX_BOOL" => "Umwandlung in einen booleschen Wert (true/false) nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_BOOL" => "Umwandlung in einen leeren Wert oder einen booleschen Wert (true/false) nicht möglich.",

        "FILTER_RULE_FAILURE_IS_CREDIT_CARD" => "Bitte eine gültige Kreditkarten-Nummer verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_CREDIT_CARD" => "Bitte keine gültige Kreditkarten-Nummer verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_CREDIT_CARD" => "Bitte frei lassen oder eine gültige Kreditkarten-Nummer verwenden.",
        "FILTER_RULE_FAILURE_FIX_CREDIT_CARD" => "Umwandlung in eine Kreditkarten-Nummer nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_CREDIT_CARD" => "Umwandlung in einen leeren Wert oder eine Kreditkarten-Nummer nicht möglich.",

        "FILTER_RULE_FAILURE_IS_DATE_TIME" => "Bitte ein gültiges Datum/Uhrzeit der Form '{format}' verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_DATE_TIME" => "Bitte kein gültiges Datum/Uhrzeit der Form '{format}' verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_DATE_TIME" => "Bitte frei lassen oder ein gültiges Datum/Uhrzeit der Form '{format}' verwenden.",
        "FILTER_RULE_FAILURE_FIX_DATE_TIME" => "Umwandlung in ein gültiges Datum/Uhrzeit der Form '{format}' nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_DATE_TIME" => "Umwandlung in einen leeren Wert oder ein gültiges Datum/Uhrzeit der Form '{format}' nicht möglich.",

        "FILTER_RULE_FAILURE_IS_EMAIL" => "Bitte eine gültige E-Mail Adresse verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_EMAIL" => "Bitte keine gültige E-Mail Adresse verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_EMAIL" => "Bitte frei lassen oder eine gültige E-Mail Adresse verwenden.",
        "FILTER_RULE_FAILURE_FIX_EMAIL" => "Umwandlung in eine gültige E-Mail Adresse nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_EMAIL" => "Umwandlung in einen leeren Wert oder eine gültige E-Mail Adresse nicht möglich.",

        "FILTER_RULE_FAILURE_IS_EQUAL_TO_FIELD" => "Bitte einen identischen Wert zu dem Feld '{other_field}' verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_EQUAL_TO_FIELD" => "Bitte keinen identischen Wert zu dem Feld '{other_field}' verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_EQUAL_TO_FIELD" => "Bitte frei lassen oder einen identischen Wert zu dem Feld '{other_field}' verwenden.",
        "FILTER_RULE_FAILURE_FIX_EQUAL_TO_FIELD" => "Umwandlung zu einem identischen Wert zu dem Feld '{other_field}' nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_EQUAL_TO_FIELD" => "Umwandlung zu einem leeren oder identischen Wert zu dem Feld '{other_field}' nicht möglich.",

        "FILTER_RULE_FAILURE_IS_EQUAL_TO_VALUE" => "Bitte den Wert '{value}' verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_EQUAL_TO_VALUE" => "Bitte nicht den Wert '{value}' verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_EQUAL_TO_VALUE" => "Bitte frei lassen oder den Wert '{value}' verwenden.",
        "FILTER_RULE_FAILURE_FIX_EQUAL_TO_VALUE" => "Umwandlung in den Wert '{value}' nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_EQUAL_TO_VALUE" => "Umwandlung in einen leeren Wert oder den Wert '{value}' nicht möglich.",

        "FILTER_RULE_FAILURE_IS_FLOAT" => "Bitte eine Dezimalzahl verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_FLOAT" => "Bitte keine Dezimalzahl verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_FLOAT" => "Bitte frei lassen oder eine Dezimalzahl verwenden.",
        "FILTER_RULE_FAILURE_FIX_FLOAT" => "Umwandlung in eine Dezimalzahl nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_FLOAT" => "Umwandlung in einen leeren Wert oder eine Dezimalzahl nicht möglich.",

        "FILTER_RULE_FAILURE_IS_IN_KEYS" => "Bitte einen der angegebene Schlüssel verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_IN_KEYS" => "Bitte keinen der angegebene Schlüssel verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_IN_KEYS" => "Bitte frei lassen oder einen der angegebene Schlüssel verwenden.",
        "FILTER_RULE_FAILURE_FIX_IN_KEYS" => "Umwandlung in einen der angegebene Schlüssel nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_IN_KEYS" => "Umwandlung in einen leeren Wert oder einen der angegebene Schlüssel nicht möglich.",

        "FILTER_RULE_FAILURE_IS_INT" => "Bitte eine Ganzzahl verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_INT" => "Bitte keine Ganzzahl verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_INT" => "Bitte frei lassen oder eine Ganzzahl verwenden.",
        "FILTER_RULE_FAILURE_FIX_INT" => "Umwandlung in eine Ganzzahl nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_INT" => "Umwandlung in einen leeren Wert oder eine Ganzzahl nicht möglich.",

        "FILTER_RULE_FAILURE_IS_IN_VALUES" => "Bitte einen der angegebenen Wert verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_IN_VALUES" => "Bitte keinen der angegebenen Wert verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_IN_VALUES" => "Bitte frei lassen oder einen der angegebenen Wert verwenden.",
        "FILTER_RULE_FAILURE_FIX_IN_VALUES" => "Umwandlung in einen der angegebenen Wert nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_IN_VALUES" => "Umwandlung in einen leeren Wert oder einen der angegebenen Wert nicht möglich.",

        "FILTER_RULE_FAILURE_IS_IPV4" => "Bitte eine gültige IPv4-Adresse verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_IPV4" => "Bitte keine gültige IPv4-Adresse verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_IPV4" => "Bitte frei lassen oder gültige IPv4-Adresse verwenden.",
        "FILTER_RULE_FAILURE_FIX_IPV4" => "Umwandlung in eine gültige IPv4-Adresse nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_IPV4" => "Umwandlung in einen leeren Wert oder eine gültige IPv4-Adresse nicht möglich.",

        "FILTER_RULE_FAILURE_IS_LOCALE" => "Bitte eine gültige Sprachkennung (z. B. de_DE, en_US) verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_LOCALE" => "Bitte keine gültige Sprachkennung (z. B. de_DE, en_US) verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_LOCALE" => "Bitte frei lassen oder eine gültige Sprachkennung (z. B. de_DE, en_US) verwenden.",
        "FILTER_RULE_FAILURE_FIX_LOCALE" => "Umwandlung in eine gültige Sprachkennung (z. B. de_DE, en_US) nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_LOCALE" => "Umwandlung in einen leeren Wert oder eine gültige Sprachkennung (z. B. de_DE, en_US) nicht möglich.",

        "FILTER_RULE_FAILURE_IS_MAX" => "Bitte maximal einen Wert von '{max}' verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_MAX" => "Bitte keinen Wert größer als '{max}' verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_MAX" => "Bitte frei lassen oder maximal einen Wert von '{max}' verwenden.",
        "FILTER_RULE_FAILURE_FIX_MAX" => "Umwandlung in einen maximalen Wert von '{max}' nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_MAX" => "Umwandlung in einen leeren Wert oder einen maximalen Wert von '{max}' nicht möglich.",

        "FILTER_RULE_FAILURE_IS_MIN" => "Bitte mindestens einen Wert von '{min}' verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_MIN" => "Bitte eine Wert kleiner als '{min}' verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_MIN" => "Bitte frei lassen oder mindestens einen Wert von '{min}' verwenden.",
        "FILTER_RULE_FAILURE_FIX_MIN" => "Umwandlung in einen Wert von mindestens '{min}' nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_MIN" => "Umwandlung in einen leeren Wert oder einen Wert von mindestens '{min}' nicht möglich.",

        "FILTER_RULE_FAILURE_IS_REGEX" => "Bitte einen Wert verwenden, der dem regulären Ausdruck '{expr}' entspricht.",
        "FILTER_RULE_FAILURE_IS_NOT_REGEX" => "Bitte einen Wert verwenden, der nicht dem regulären Ausdruck '{expr}' entspricht.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_REGEX" => "Bitte frei lassen oder einen Wert verwenden, der dem regulären Ausdruck '{expr}' entspricht.",
        "FILTER_RULE_FAILURE_FIX_REGEX" => "Umwandlung in einen Wert, der dem regulären Ausdruck '{expr}' entspricht, nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_REGEX" => "Umwandlung in einen leeren Wert oder einen Wert, der dem regulären Ausdruck '{expr}' entspricht, nicht möglich.",

        "FILTER_RULE_FAILURE_IS_STRICT_EQUAL_TO_FIELD" => "Bitte einen identischen Wert zu dem Feld '{other_field}' verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_STRICT_EQUAL_TO_FIELD" => "Bitte keinen identischen Wert zu dem Feld '{other_field}' verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRICT_EQUAL_TO_FIELD" => "Bitte frei lassen oder einen identischen Wert zu dem Feld '{other_field}' verwenden.",
        "FILTER_RULE_FAILURE_FIX_STRICT_EQUAL_TO_FIELD" => "Umwandlung in einen identischen Wert zu dem Feld '{other_field} nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRICT_EQUAL_TO_FIELD" => "Umwandlung in einen leeren Wert oder einen identischen Wert zu dem Feld '{other_field} nicht möglich.",

        "FILTER_RULE_FAILURE_IS_STRICT_EQUAL_TO_VALUE" => "Bitte einen identischen Wert zu '{value}' verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_STRICT_EQUAL_TO_VALUE" => "Bitte keinen identischen Wert zu '{value}' verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRICT_EQUAL_TO_VALUE" => "Bitte frei lassen oder einen identischen Wert zu '{value}' verwenden.",
        "FILTER_RULE_FAILURE_FIX_STRICT_EQUAL_TO_VALUE" => "Umwandlung in einen identischen Wert zu '{value}' nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRICT_EQUAL_TO_VALUE" => "Umwandlung in einen leeren Wert oder einen identischen Wert zu '{value}' nicht möglich.",

        "FILTER_RULE_FAILURE_IS_STRING" => "Bitte einen Text-String verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_STRING" => "Bitte keinen Text-String verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRING" => "Bitte frei lassen oder einen Text-String verwenden.",
        "FILTER_RULE_FAILURE_FIX_STRING" => "Umwandlung in einen Text-String nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRING" => "Umwandlung in einen leeren Wert oder einen Text-String nicht möglich.",

        "FILTER_RULE_FAILURE_IS_STRLEN" => "Bitte {len} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN" => "Bitte keine {len} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN" => "Bitte frei lassen oder {len} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_FIX_STRLEN" => "Umwandlung zu {strlen} Zeichen nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN" => "Umwandlung in einen leeren Wert oder zu {strlen} Zeichen nicht möglich.",

        "FILTER_RULE_FAILURE_IS_STRLEN_BETWEEN" => "Bitte zwischen {min} und {max} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN_BETWEEN" => "Bitte keine {min} bis {max} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN_BETWEEN" => "Bitte frei lassen oder zwischen {min} und {max} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_FIX_STRLEN_BETWEEN" => "Umwandlung in einen Wert von {min} bis {max} Zeichen nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN_BETWEEN" => "Umwandlung in einen leeren oder Wert von {min} bis {max} Zeichen nicht möglich.",

        "FILTER_RULE_FAILURE_IS_STRLEN_MAX" => "Bitte nicht mehr als {max} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN_MAX" => "Bitte mehr als {max} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN_MAX" => "Bitte frei lassen oder nicht mehr als {max} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_FIX_STRLEN_MAX" => "Umwandlung in einen Wert von nicht mehr als {max} Zeichen nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN_MAX" => "Umwandlung in einen leeren oder Wert von nicht mehr als {max} Zeichen nicht möglich.",

        "FILTER_RULE_FAILURE_IS_STRLEN_MIN" => "Bitte mindestens {min} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN_MIN" => "Bitte nicht mehr {min} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN_MIN" => "Bitte frei lassen oder mindestens {min} Zeichen verwenden.",
        "FILTER_RULE_FAILURE_FIX_STRLEN_MIN" => "Umwandlung in einen Wert von mindestens {min} Zeichen nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN_MIN" => "Umwandlung in einen leeren oder Wert von mindestens {min} Zeichen nicht möglich.",

        "FILTER_RULE_FAILURE_IS_TRIM" => "Bitte Leerzeichen am Anfang und Ende entfernen.",
        "FILTER_RULE_FAILURE_IS_NOT_TRIM" => "Bitte Leerzeichen am Anfang und Ende hinzufügen.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_TRIM" => "Bitte frei lassen oder Leerzeichen am Anfang und Ende entfernen.",
        "FILTER_RULE_FAILURE_FIX_TRIM" => "Entfernung von Leerzeichen am Anfang und Ende nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_TRIM" => "Umwandlung in einen leeren Wert oder Entfernung von Leerzeichen am Anfang und Ende nicht möglich.",

        "FILTER_RULE_FAILURE_IS_UPLOAD" => "Bitte eine Datei hochladen.",
        "FILTER_RULE_FAILURE_IS_NOT_UPLOAD" => "Bitte keine Datei hochladen.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_UPLOAD" => "Bitte frei lassen oder eine Datei hochladen.",
        "FILTER_RULE_FAILURE_FIX_UPLOAD" => "Umwandlung in eine hochzuladende Datei nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_UPLOAD" => "Umwandlung in einen leeren Wert oder eine hochzuladende Datei nicht möglich.",
        "FILTER_RULE_ERR_UPLOAD_INI_SIZE" => "Die hochgeladene Datei übersteigt den upload_max_filesize Wert in der php.ini.",
        "FILTER_RULE_ERR_UPLOAD_FORM_SIZE" => "Die hochgeladene Datei übersteigt den MAX_FILE_SIZE Wert in dem HTML Formular.",
        "FILTER_RULE_ERR_UPLOAD_PARTIAL" => "Die Datei wurde nur teilweise hochgeladen.",
        "FILTER_RULE_ERR_UPLOAD_NO_FILE" => "Es wurde keine Datei hochgeladen.",
        "FILTER_RULE_ERR_UPLOAD_NO_TMP_DIR" => "Kein temporäres Verzeichnis vorhanden, um die hochgeladene Datei zu speichern.",
        "FILTER_RULE_ERR_UPLOAD_CANT_WRITE" => "Die hochgeladene Datei konnte nicht auf der Festplatte gespeichert werden.",
        "FILTER_RULE_ERR_UPLOAD_EXTENSION" => "Eine PHP-Erweiterung hat das Hochladen der Datei verhindert.",
        "FILTER_RULE_ERR_UPLOAD_UNKNOWN" => "Es trat ein unbekannter Fehler beim Hochladen der Datei auf.",
        "FILTER_RULE_ERR_UPLOAD_IS_UPLOADED_FILE" => "Bei der Datei handelt es sich nicht um eine hochgeladene Datei.",
        "FILTER_RULE_ERR_UPLOAD_ARRAY_KEYS" => "Der Array des Hochladen-Vorgangs ist fehlerhaft formatiert.",

        "FILTER_RULE_FAILURE_IS_URL" => "Bitte eine gültige URL angeben.",
        "FILTER_RULE_FAILURE_IS_NOT_URL" => "Bitte keine gültige URL angeben.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_URL" => "Bitte frei lassen oder eine gültige URL angeben.",
        "FILTER_RULE_FAILURE_FIX_URL" => "Umwandlung in eine gültige URL nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_URL" => "Umwandlung in einen leeren Wert oder eine gültige URL nicht möglich.",

        "FILTER_RULE_FAILURE_IS_WORD" => "Bitte nur gültige Wortzeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_NOT_WORD" => "Bitte nicht nur gültige Wortzeichen verwenden.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_WORD" => "Bitte frei lassen oder nur gültige Wortzeichen verwenden.",
        "FILTER_RULE_FAILURE_FIX_WORD" => "Umwandlung in nur gültige Wortzeichen nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_WORD" => "Umwandlung in einen leeren Wert oder nur gültige Wortzeichen nicht möglich.",

        "FILTER_RULE_FAILURE_IS_ISBN" => "Bitte gültige ISBN angeben.",
        "FILTER_RULE_FAILURE_IS_NOT_ISBN" => "Bitte keine gültige ISBN angeben.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_ISBN" => "Bitte frei lassen oder gültige ISBN angeben.",
        "FILTER_RULE_FAILURE_FIX_ISBN" => "Umwandlung in eine gültige ISBN nicht möglich.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_ISBN" => "Umwandlung in einen leeren Wert oder eine gültige ISBN nicht möglich.",
    ],
);
