<?php
return array(
    "fallback" => null,
    "formatter" => "basic",
    "messages" => [
    
        "FILTER_RULE_FAILURE_IS_ALNUM" => "Please use only alphanumeric characters.",
        "FILTER_RULE_FAILURE_IS_NOT_ALNUM" => "Please do not use only alphanumeric characters.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_ALNUM" => "Please leave blank, or use only alphanumeric characters.",
        "FILTER_RULE_FAILURE_FIX_ALNUM" => "Could not sanitize to only alphanumeric characters.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_ALNUM" => "Could not sanitize to a blank or only alphanumeric characters.",

        "FILTER_RULE_FAILURE_IS_ALPHA" => "Please use only alphabetic characters.",
        "FILTER_RULE_FAILURE_IS_NOT_ALPHA" => "Please do not use only alphabetic characters.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_ALPHA" => "Please leave blank, or use only alphabetic characters.",
        "FILTER_RULE_FAILURE_FIX_ALPHA" => "Could not sanitize to only alphabetic characters.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_ALPHA" => "Could not sanitize to a blank or only alphabetic characters.",

        "FILTER_RULE_FAILURE_IS_ANY" => "This field did not pass any of the sub-rules.",
        "FILTER_RULE_FAILURE_IS_NOT_ANY" => "This field should not have passed any of the sub-rules.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_ANY" => "Please leave blank, or change so it passes one of the sub-rules.",
        "FILTER_RULE_FAILURE_FIX_ANY" => "Could not sanitize this field.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_ANY" => "Could not sanitize this field.",

        "FILTER_RULE_FAILURE_IS_BETWEEN" => "Please use a value between {min} and {max}.",
        "FILTER_RULE_FAILURE_IS_NOT_BETWEEN" => "Please do not use a value between {min} and {max}.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_BETWEEN" => "Please leave blank, or use a value between {min} and {max}.",
        "FILTER_RULE_FAILURE_FIX_BETWEEN" => "Could not sanitize this field to a value between {min} and {max}.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_BETWEEN" => "Could not sanitize this field to blank or a value between {min} and {max}",

        "FILTER_RULE_FAILURE_IS_BLANK" => "Please leave this blank.",
        "FILTER_RULE_FAILURE_IS_NOT_BLANK" => "Please do not leave this blank.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_BLANK" => "Please leave this blank.",
        "FILTER_RULE_FAILURE_FIX_BLANK" => "Could not sanitize to blank.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_BLANK" => "Could not sanitize to blank.",

        "FILTER_RULE_FAILURE_IS_BOOL" => "Please use a boolean (true/false) value.",
        "FILTER_RULE_FAILURE_IS_NOT_BOOL" => "Please do not use a boolean (true/false) value.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_BOOL" => "Please leave blank, or use a boolean (true/false) value.",
        "FILTER_RULE_FAILURE_FIX_BOOL" => "Could not sanitize to a boolean (true/false) value.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_BOOL" => "Could not sanitize to blank or a boolean (true/false) value.",

        "FILTER_RULE_FAILURE_IS_CREDIT_CARD" => "Please use a valid credit card number.",
        "FILTER_RULE_FAILURE_IS_NOT_CREDIT_CARD" => "Please do not use a credit card number.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_CREDIT_CARD" => "Please leave blank, or use a valid credit card number.",
        "FILTER_RULE_FAILURE_FIX_CREDIT_CARD" => "Could not sanitize to a credit card number.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_CREDIT_CARD" => "Could not sanitize to blank or a credit card number.",

        "FILTER_RULE_FAILURE_IS_DATE_TIME" => "Please use a valid date/time value in the format '{format}'.",
        "FILTER_RULE_FAILURE_IS_NOT_DATE_TIME" => "Please do not use a date/time value in the format '{format}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_DATE_TIME" => "Please leave blank or use a valid date/time value in the format '{format}'.",
        "FILTER_RULE_FAILURE_FIX_DATE_TIME" => "Could not sanitize to a date/time value in the format '{format}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_DATE_TIME" => "Could not sanitize to blank or a date/time value in the format '{format}'.",

        "FILTER_RULE_FAILURE_IS_EMAIL" => "Please use a valid email address.",
        "FILTER_RULE_FAILURE_IS_NOT_EMAIL" => "Please do not use a valid email address.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_EMAIL" => "Please leave blank or use a valid email address.",
        "FILTER_RULE_FAILURE_FIX_EMAIL" => "Could not sanitize to an email address.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_EMAIL" => "Could not sanitize to blank or a valid email address.",

        "FILTER_RULE_FAILURE_IS_EQUAL_TO_FIELD" => "Please use a value equal to the field '{field}'.",
        "FILTER_RULE_FAILURE_IS_NOT_EQUAL_TO_FIELD" => "Please do not use a value equal to the field '{field}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_EQUAL_TO_FIELD" => "Please leave blank or use a value equal to the field '{field}'.",
        "FILTER_RULE_FAILURE_FIX_EQUAL_TO_FIELD" => "Could not sanitize to a value equal to the field '{field}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_EQUAL_TO_FIELD" => "Could not sanitize to blank or a value equal to the field '{field}'.",

        "FILTER_RULE_FAILURE_IS_EQUAL_TO_VALUE" => "Please use the value '{value}'.",
        "FILTER_RULE_FAILURE_IS_NOT_EQUAL_TO_VALUE" => "Please do not use the value '{value}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_EQUAL_TO_VALUE" => "Please leave blank or use the value '{value}'.",
        "FILTER_RULE_FAILURE_FIX_EQUAL_TO_VALUE" => "Could not sanitize to '{value}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_EQUAL_TO_VALUE" => "Could not sanitize to blank or '{value}'.",

        "FILTER_RULE_FAILURE_IS_FLOAT" => "Please use a decimal number.",
        "FILTER_RULE_FAILURE_IS_NOT_FLOAT" => "Please do not use a decimal number.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_FLOAT" => "Please leave blank or use a decimal number.",
        "FILTER_RULE_FAILURE_FIX_FLOAT" => "Could not sanitize to a decimal number.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_FLOAT" => "Could not sanitize to blank or a decimal number.",

        "FILTER_RULE_FAILURE_IS_IN_KEYS" => "Please use a listed key.",
        "FILTER_RULE_FAILURE_IS_NOT_IN_KEYS" => "Please do not use a listed key.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_IN_KEYS" => "Please leave blank or use a listed key.",
        "FILTER_RULE_FAILURE_FIX_IN_KEYS" => "Could not sanitize to a listed key.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_IN_KEYS" => "Could not sanitize to blank or a listed key.",

        "FILTER_RULE_FAILURE_IS_INT" => "Please use a whole number.",
        "FILTER_RULE_FAILURE_IS_NOT_INT" => "Please do not use a whole number.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_INT" => "Please leave blank or use a whole number.",
        "FILTER_RULE_FAILURE_FIX_INT" => "Could not sanitize to a whole number.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_INT" => "Could not sanitize to blank or a whole number.",

        "FILTER_RULE_FAILURE_IS_IN_VALUES" => "Please use a listed value.",
        "FILTER_RULE_FAILURE_IS_NOT_IN_VALUES" => "Please do not use a listed value.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_IN_VALUES" => "Please leave blank or use a listed value.",
        "FILTER_RULE_FAILURE_FIX_IN_VALUES" => "Could not sanitize to a listed value.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_IN_VALUES" => "Could not sanitize to blank or a listed value.",

        "FILTER_RULE_FAILURE_IS_IPV4" => "Please use a valid IPv4 address.",
        "FILTER_RULE_FAILURE_IS_NOT_IPV4" => "Please do not use a valid IPv4 address.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_IPV4" => "Please leave blank or use a valid IPv4 address.",
        "FILTER_RULE_FAILURE_FIX_IPV4" => "Could not sanitize to an IPv4 address.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_IPV4" => "Could not sanitize to blank or an IPv4 address.",

        "FILTER_RULE_FAILURE_IS_LOCALE" => "Please use a valid locale code.",
        "FILTER_RULE_FAILURE_IS_NOT_LOCALE" => "Please do not use a valid locale code.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_LOCALE" => "Please leave blank or use a valid locale code.",
        "FILTER_RULE_FAILURE_FIX_LOCALE" => "Could not sanitize to a valid locale code.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_LOCALE" => "Could not sanitize to blank or a valid locale code.",

        "FILTER_RULE_FAILURE_IS_MAX" => "Please use a maximum value of '{max}'.",
        "FILTER_RULE_FAILURE_IS_NOT_MAX" => "Please use a value greater than '{max}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_MAX" => "Please leave blank or use a maximum value of '{max}'.",
        "FILTER_RULE_FAILURE_FIX_MAX" => "Could not sanitize to a maximum value of '{max}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_MAX" => "Could not sanitize to blank or a maximum value of '{max}'.",

        "FILTER_RULE_FAILURE_IS_MIN" => "Please use a minimum value of '{min}'.",
        "FILTER_RULE_FAILURE_IS_NOT_MIN" => "Please use a value less than '{min}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_MIN" => "Please leave blank or use a minimum value of '{min}'.",
        "FILTER_RULE_FAILURE_FIX_MIN" => "Could not sanitize to a minimum value of '{min}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_MIN" => "Could not sanitize to blank or a minimum value of '{min}'.",

        "FILTER_RULE_FAILURE_IS_REGEX" => "Please use a value that matches the pattern '{regex}'.",
        "FILTER_RULE_FAILURE_IS_NOT_REGEX" => "Please use a value that does not match the pattern '{regex}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_REGEX" => "Please leave blank or use a value that matches the pattern '{regex}'.",
        "FILTER_RULE_FAILURE_FIX_REGEX" => "Could not sanitize to the pattern '{regex}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_REGEX" => "Could not sanitize to blank or the pattern '{regex}'.",

        "FILTER_RULE_FAILURE_IS_STRICT_EQUAL_TO_FIELD" => "Please use a value identical to the field '{field}'.",
        "FILTER_RULE_FAILURE_IS_NOT_STRICT_EQUAL_TO_FIELD" => "Please use a value that is not identical to the field '{field}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRICT_EQUAL_TO_FIELD" => "Please leave blank or use a value identical to the field '{field}'.",
        "FILTER_RULE_FAILURE_FIX_STRICT_EQUAL_TO_FIELD" => "Could not sanitize to a value identical to the field '{field}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRICT_EQUAL_TO_FIELD" => "Could not sanitize to blank or a value identical to the field '{field}'.",

        "FILTER_RULE_FAILURE_IS_STRICT_EQUAL_TO_VALUE" => "Please use a value identical to '{value}'.",
        "FILTER_RULE_FAILURE_IS_NOT_STRICT_EQUAL_TO_VALUE" => "Please do not use a value identical to '{value}'.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRICT_EQUAL_TO_VALUE" => "Please leave blank or use a value identical to '{value}'.",
        "FILTER_RULE_FAILURE_FIX_STRICT_EQUAL_TO_VALUE" => "Could not sanitize to a value identical to '{value}'.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRICT_EQUAL_TO_VALUE" => "Could not sanitize to blank or a value identical to '{value}'.",

        "FILTER_RULE_FAILURE_IS_STRING" => "Please use a string of text.",
        "FILTER_RULE_FAILURE_IS_NOT_STRING" => "Please do not use a string of text.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRING" => "Please leave blank or use a string a text.",
        "FILTER_RULE_FAILURE_FIX_STRING" => "Could not sanitize to a string of text.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRING" => "Could not sanitize to blank or a string of text.",

        "FILTER_RULE_FAILURE_IS_STRLEN" => "Please use {len} character(s).",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN" => "Please do not use {len} character(s).",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN" => "Please leave blank or use {len} characters.",
        "FILTER_RULE_FAILURE_FIX_STRLEN" => "Could not sanitize to {strlen} characters.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN" => "Could not sanitize to blank or {strlen} characters.",

        "FILTER_RULE_FAILURE_IS_STRLEN_BETWEEN" => "Please use between {min} and {max} characters.",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN_BETWEEN" => "Please do not use between {min} and {max} characters.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN_BETWEEN" => "Please leave blank or use between {min} and {max} characters.",
        "FILTER_RULE_FAILURE_FIX_STRLEN_BETWEEN" => "Could not sanitize to between {min} and {max} characters.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN_BETWEEN" => "Could not sanitize to blank or between {min} and {max} characters.",

        "FILTER_RULE_FAILURE_IS_STRLEN_MAX" => "Please use no more than than {max} character(s).",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN_MAX" => "Please use more than {max} character(s).",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN_MAX" => "Please leave blank or use no more than {max} character(s).",
        "FILTER_RULE_FAILURE_FIX_STRLEN_MAX" => "Could not sanitize to no more than {max} characters.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN_MAX" => "Could not sanitize to blank or no more than {max} characters.",

        "FILTER_RULE_FAILURE_IS_STRLEN_MIN" => "Please use at least {min} character(s).",
        "FILTER_RULE_FAILURE_IS_NOT_STRLEN_MIN" => "Please use no more than {min} character(s).",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_STRLEN_MIN" => "Please use at least {min} character(s).",
        "FILTER_RULE_FAILURE_FIX_STRLEN_MIN" => "Could not sanitize to at least {min} character(s).",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_STRLEN_MIN" => "Could not sanitize to blank or at least {min} character(s).",

        "FILTER_RULE_FAILURE_IS_TRIM" => "Please omit whitepspace padding.",
        "FILTER_RULE_FAILURE_IS_NOT_TRIM" => "Please use whitepspace padding.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_TRIM" => "Please leave blank or omit whitespace padding.",
        "FILTER_RULE_FAILURE_FIX_TRIM" => "Could not sanitize whitespace padding.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_TRIM" => "Could not sanitize to blank or remove whitespace padding.",

        "FILTER_RULE_FAILURE_IS_UPLOAD" => "Please upload a file.",
        "FILTER_RULE_FAILURE_IS_NOT_UPLOAD" => "Please do not upload a file.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_UPLOAD" => "Please leave blank or upload a file.",
        "FILTER_RULE_FAILURE_FIX_UPLOAD" => "Could not sanitize uploaded file.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_UPLOAD" => "Could not sanitize to blank or uploaded file.",
        "FILTER_RULE_ERR_UPLOAD_INI_SIZE" => "The uploaded file exceeds the upload_max_filesize in php.ini.",
        "FILTER_RULE_ERR_UPLOAD_FORM_SIZE" => "The uploaded file exceeds the MAX_FILE_SIZE in the HTML form.",
        "FILTER_RULE_ERR_UPLOAD_PARTIAL" => "The uploaded file was only partially uploaded.",
        "FILTER_RULE_ERR_UPLOAD_NO_FILE" => "No file was uploaded.",
        "FILTER_RULE_ERR_UPLOAD_NO_TMP_DIR" => "No temporory directory to save uploaded file.",
        "FILTER_RULE_ERR_UPLOAD_CANT_WRITE" => "Failed to write uploaded file to disk.",
        "FILTER_RULE_ERR_UPLOAD_EXTENSION" => "A PHP extension stopped the file upload.",
        "FILTER_RULE_ERR_UPLOAD_UNKNOWN" => "An unknown error prevented the upload.",
        "FILTER_RULE_ERR_UPLOAD_IS_UPLOADED_FILE" => "The file is not an uploaded file.",
        "FILTER_RULE_ERR_UPLOAD_ARRAY_KEYS" => "The upload array is malformed.",

        "FILTER_RULE_FAILURE_IS_URL" => "Please enter a valid URL.",
        "FILTER_RULE_FAILURE_IS_NOT_URL" => "Please do not enter a valid URL.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_URL" => "Please leave blank or enter a valid URL.",
        "FILTER_RULE_FAILURE_FIX_URL" => "Could not sanitize to a valid URL.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_URL" => "Could not sanitize to blank or a valid URL.",

        "FILTER_RULE_FAILURE_IS_WORD" => "Please use only word characters.",
        "FILTER_RULE_FAILURE_IS_NOT_WORD" => "Please do not use only word characters.",
        "FILTER_RULE_FAILURE_IS_BLANK_OR_WORD" => "Please leave blank or use only word characters.",
        "FILTER_RULE_FAILURE_FIX_WORD" => "Could not sanitize to only word characters.",
        "FILTER_RULE_FAILURE_FIX_BLANK_OR_WORD" => "Could not sanitize to blank or only word characters.",
    ],
);
